### ISSUE TITLE
Build fails in src/ata_id

### ISSUE THREAD

**Issue by tseeker** [gentoo/eudev#102]
Compilation fails on src/ata_id/ata_id.c due to missing headers:

    In file included from ata_id.c:50:0:
    ../../src/shared/udev-util.h:22:18: fatal error: udev.h: No such file or directory
     #include "udev.h"

**Comment by blueness** [comment]
I see your point here, but I'm just not hitting a compile error. Can you tell me how you are building so I can see why you hit the problem and I do not.

**Comment by tseeker** [comment]
I've tried building it using:

    ./autogen.sh
    ./configure --with-rootprefix= --with-rootlibdir=/lib/x86_64-linux-gnu --with-rootlibexecdir=/lib/udev --exec-prefix=/ --enable-split-usr --disable-selinux --enable-libkmod --enable-introspection --enable-gtk-doc
    make -j4

Since that didn't work, I also tried running the configure script with no options, and the make with just 1 job. Full clean-up + git reset --hard between attempts. None of the combinations worked.

I'm running this on a Debian sid/amd64 box (automake 1.14.1, autoconf 2.69, libtool 2.4.2, gcc 4.9.2). All build dependencies are installed.

**Comment by fluxer** [comment]
@blueness 
The issue is reproducable on systems where udev.h is not in the system headers path, e.g. /usr/include/udev.h is not present.

I have not tested the patch from #103 but I guess it will fix the problem.

**Comment by blueness** [comment]
@fluxer
Doh!  Obviously that's why I'm not hitting it.  I'll merge the pull request now.

**Comment by blueness** [comment]
@tseeker.  Thanks.  Please test and let me know if anything else is wrong.
