### ISSUE TITLE
Make an option to disable hwdb.d installation

### ISSUE THREAD

**Issue by yegorich** [gentoo/eudev#111]
hwdb.d installation occupies about 5Mb disk space. For some small embedded projects, especially, when run from a NAND flash, it is a huge overhead. It would helpful to have a configure option to disable hwdb.d installation.

**Comment by blueness** [comment]
I'll see what I can do for the next release.

**Comment by blueness** [comment]
Okay, --{enable,disable}-hwdb was added in commit ebb37f6a47f64314a81b40e3befbe3fc9ced8f4a.  The default is --enable-hwdb since most people will want that.  The new feature will be out in 3.1 which should be available in a day or so.
