### ISSUE TITLE
eudev-3.1 missing 80-net-name-slot.rules, won't rename ifaces

### ISSUE THREAD

**Issue by axs-gentoo** [gentoo/eudev#117]
Because eudev doesn't implement the net-setup-link module, without 80-net-name-slot.rules (or integration of this rules file's contents into 75-net-description.rules) eudev-3.1 won't rename interfaces with the persistent name as calculated by the net_id builtin.

Simplest fix would likely be to continue distributing the 80-net-name-slot.rules file, thus allowing the old /etc/udev/rules.d symlink-to-/dev/null method of disabling.

**Comment by blueness** [comment]
Thanks, I already got that report from several angles!  I'll be pushing out 3.1.1 with the fix in a bit.

**Comment by blueness** [comment]
This is fixed as of git head and will be out in 3.1.1 which I'm preparing now.
