### ISSUE TITLE
Custom hwdb file no longer used by eudev 3.1.1

### ISSUE THREAD

**Issue by MorLipf** [gentoo/eudev#118]
I am using a custom hwdb file for remapping some keys of my notebook's (Dell XPS 15) keyboard:

keyboard:dmi:bvn*:bvr*:bd*:svnDell*:pnDellSystemXPS*:pvr*
 KEYBOARD_KEY_85=prog1
 KEYBOARD_KEY_84=prog2

This file works fine with eudev 3.0. After the upgrade to version 3.1.1 this file seems no longer to be respected by udev. Re-applying the command "udevadm hwdb --update" has no effect.

Is this a bug or do I have to alter my hwdb file?

**Comment by blueness** [comment]
The problem is that `keyboard` was replaced by `evdev'.  Take a look at 60-keyboard.hwdb as a model.  Let me know if you still have a problem after that.

**Comment by MorLipf** [comment]
I missed that point. Now it is working again. Thanks!
