### ISSUE TITLE
The Wacom CTH-460 is not a joystick (likely applies to other tablets)

### ISSUE THREAD

**Issue by ShadowKyogre** [gentoo/eudev#120]
The culprit code: https://github.com/gentoo/eudev/blob/10647c881b4d2740a226cb954cf4b91c6e462907/src/udev/udev-builtin-input_id.c#L173-L184

My attempt at fixing it with the udev rules generated with libwacom's ```generate-udev-rules```: https://gist.github.com/ShadowKyogre/3e3b4d347f71a97a1956#file-99-fix-wacom-really-rules-L138-L141

Here's the mailing list indicator indicating the issue with udev's joystick detection: http://sourceforge.net/p/linuxwacom/mailman/message/33349499/

Even though I tried forcing udev to say it's not a joystick despite this, it still refuses to treat it as not-a-joystick because it still shows up as ```/dev/input/js${some_number}```

**Comment by ShadowKyogre** [comment]
https://gist.github.com/ShadowKyogre/3e3b4d347f71a97a1956#file-udev-my-tablet-is-not-a-joystick-txt Here's the output of ```udevadm monitor -p```

**Comment by ShadowKyogre** [comment]
Did some more research and it turns out it's a kernel bug. I found this out by killing udev and noticing the phantom joystick was still being created: https://gist.github.com/denilsonsa/978f1d842cf5430f57f6

**Comment by blueness** [comment]
So I don't think there's anything for eudev to do here.

**Comment by ShadowKyogre** [comment]
Yeah ^^;. I noticed that belatedly. I'll go ahead and close it.
