### ISSUE TITLE
dmesg shows a lot of "udevd[xxx]: worker [xxx] is unknown, ignoring" messages

### ISSUE THREAD

**Issue by anto** [gentoo/eudev#121]
After merging the commits newer than commit c9ed0f0dc661d272d296276fdfb10e60ab278409 (except commit 1b6370e74bd6927a5c594210cd6728feda9c4616, 252150e181c58c5ae58ffac144971767df9921f7, 3df635050b4068089d5477b9423de06c6a39bdee and 2cf24b397833998869718043fb000013b1a43832), every time after I reboot my PC dmesg shows ***udevd[xxx]: worker [xxx] is unknown, ignoring*** messages as below which does not happen on eudev package up to commit c9ed0f0dc661d272d296276fdfb10e60ab278409.

```
.
.
[    0.788774] Freeing unused kernel memory: 1140K (ffff8800014e3000 - ffff880001600000)
[    0.789636] Freeing unused kernel memory: 364K (ffff8800017a5000 - ffff880001800000)
[    0.851871] udevd[71]: starting version 3.1.2
[    0.852184] random: udevd urandom read with 2 bits of entropy available
[    0.858139] udevd[72]: worker [72] is unknown, ignoring 
[    0.858297] udevd[72]: worker [72] is unknown, ignoring
.
.
[    2.532542] udevd[72]: worker [72] is unknown, ignoring 
[    2.532607] udevd[72]: worker [72] is unknown, ignoring
[    2.706285] PM: Starting manual resume from disk     
[    2.706288] PM: Hibernation image partition 8:3 present
[    2.706289] PM: Looking for hibernation image. 
[    2.706482] PM: Image not found (code -22)
[    2.706484] PM: Hibernation image not present or could not be loaded.
[    2.748870] udevd[72]: worker [72] is unknown, ignoring 
[    2.749115] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[    2.772972] Switched to clocksource tsc
[    3.277085] udevd[302]: starting version 3.1.2
[    3.405112] udevd[303]: worker [303] is unknown, ignoring
[    3.405360] udevd[303]: worker [303] is unknown, ignoring
.
.
```
I am not sure if that was due to I excluded the 4 commits above. So it would be great if somebody else could confirm whether this issue happen also on other setups or not.

In the mean time, I rolled back to commit c9ed0f0dc661d272d296276fdfb10e60ab278409.

**Comment by anto** [comment]
I have just merged all 33 new commits and dmesg still shows a lot of "udevd[xxx]: worker [xxx] is unknown, ignoring" messages. This confirms that the problem is not because I excluded the 4 commits that I previously mentioned.

It would be great if somebody could give me suggestions to practically debug this. Because debugging this issue by cherry-picking individual commit, compile, install and reboot for 33 times is definitely not practical.

**Comment by fluxer** [comment]
75e930ed seems to be the cause, I have not done any testing to confirm this but it pops the same message you describe. Hope this helps.

Cheers!

**Comment by anto** [comment]
Thanks a lot fluxer for the hint.

I can confirm that commit 75e930ed64b62ac7e684cbe3493963371904d55b is to blame for this problem. After deleting this particular commit, recompiling, installing and rebooting my PC, I don't see the message anymore on dmesg output.

It would be better if we could get better information about the untracked worker, so we could take relevant actions. Unfortunately, I have no clue on the detail of how udevd actually works so I cannot offer better solution.

**Comment by blueness** [comment]
sorry for the delay, real life.  i see what's going on and yeah we need to revert that.  usptream had clearly gone in a direction we can't follow, so ...

**Comment by blueness** [comment]
Please test and reopen if this is still a problem.
