### ISSUE TITLE
make check fails Can't exec "tree"

### ISSUE THREAD

**Issue by ketilwright** [gentoo/eudev#128]
I am building eudev as part of LFS 7.8, and receive the following test failure(s).

Perhaps this should be expected, as tree is not available (yet).

FAIL: udev-test.pl
==================

udev-test will run 137 tests:

TEST 1: no rules
device '/devices/pci0000:00/0000:00:1f.2/host0/target0:0:0/0:0:0:0/block/sda' expecting node/link 'sda'
failed to mount / as private: Invalid argument
add:         error
Can't exec "tree": No such file or directory at ./udev-test.pl line 1444.

failed to mount / as private: Invalid argument
remove:      ok

TEST 2: label test of scsi disc
device '/devices/pci0000:00/0000:00:1f.2/host0/target0:0:0/0:0:0:0/block/sda' expecting node/link 'boot_disk'
failed to mount / as private: Invalid argument
add:         error
Can't exec "tree": No such file or directory at ./udev-test.pl line 1444.

failed to mount / as private: Invalid argument
remove:      ok

... etc

**Comment by blueness** [comment]
This is not a bug.  If you don't have `tree` available, then system('tree', ....) is going to fail.  I would update the LFS docs and just alert the user to this fact.  But there is nothing for me to do here.
