### ISSUE TITLE
Triggering Udev Events Hangs On Cold Start... 

### ISSUE THREAD

**Issue by Geyup** [gentoo/eudev#135]
This was originally happening with Udev, but now Slackware 14.2 has swithced over to eudev, I wanted to report this issue here, in hopes of a fix, or solution...

https://bugzilla.kernel.org/show_bug.cgi?id=119411

thanks

**Comment by blueness** [comment]
I read that bug report and I don't think its a udev/eudev bug.  It sounds like some flaky hardware issue.  Without anymore information this bug report is going to be dead in the water.

**Comment by Geyup** [comment]
This sounds like you're guessing without any leg work troubleshooting...

Flaky hardware hasn't been determined, and I don't even know, nor have I found anyone that does know how to trobuleshoot this issue, to determine flaky hardware, or if it's really a bug.

So if you really know a way in which this can be done, to actually determine if it's truly not just my hardware, or truly not a udev/eudev issues, I'd greatly appreciate this report being left open.

Because everything now is just speculation...

I personally thought this was more a kernel issue, because I never saw it until using 4.4x versions...

**Comment by blueness** [comment]
if you think its the kernel, do a git bisect and find what commit introduced the problem.  its not udev.

**Comment by Geyup** [comment]
I'd like to be able to figure out, if possible how to look what's happening with the below commands, when it comes to these at bootup, to see what's causing it to hang, rather then a bisect...

 # Since udev is just now being started we want to use add events:
          echo "Triggering udev events:  /sbin/udevadm trigger --action=add"
          # Call udevtrigger and udevsettle to do the device configuration:
          /sbin/udevadm trigger --type=subsystems --action=add
          /sbin/udevadm trigger --type=devices --action=add

**Comment by EvaSDK** [comment]
bissecting the kernel is really the fastest way to know what caused the problem to appear if you think this is kernel related. It seems hard but it really isn't that much. A lot less hassle than trying to workaround it in my opinion.
