### ISSUE TITLE
udev_device_get_parent_with_subsystem_devtype crashes with certain devices

### ISSUE THREAD

**Issue by laenion** [gentoo/eudev#141]
A lot of Unity games crash on startup when they are using the Rewired library for input handling. According to the developer this crash is caused when calling function `udev_device_get_parent_with_subsystem_devtype` with "certain devices" (see https://forum.unity3d.com/threads/rewired-advanced-input-for-unity.270693/page-48#post-2775049 for the full post). This only happens with eudev, but not with systemd-udev.

Three of those "certain devices" are the EMS Trio Linker Plus 2 (a gamepad converter), a cheap DragonRise SNES style gamepad and the Bliss-Box - i.e. all gamepads that I own. Games that are affected include "The Dwarves", "The Long Dark", the "Shadow Tactics" demo (https://www.gog.com/game/shadow_tactics_demo) and "Guts and Glory" (http://www.indiedb.com/games/guts-and-glory/downloads/guts-and-glory-v032-linux; available for free without registration, so probably the best test candidate).

While the developer worked around this with a new version, probably not all games will be updated, so this should still be fixed in eudev.

**Comment by laenion** [comment]
After some debugging I think I can narrow this problem down to the following: Slackware64 14.2 has two versions of libudev installed:
```
lrwxrwxrwx 1 root root     17 Jun 25  2016 /lib64/libudev.so.0 -> libudev.so.0.13.1
-rwxr-xr-x 1 root root  53968 Sep 26  2013 /lib64/libudev.so.0.13.1
lrwxrwxrwx 1 root root     16 Jun 25  2016 /lib64/libudev.so.1 -> libudev.so.1.6.3
-rwxr-xr-x 1 root root 149720 Jan 12  2016 /lib64/libudev.so.1.6.3
lrwxrwxrwx 1 root root     28 Feb 20  2016 /usr/lib64/libudev.so -> ../../lib64/libudev.so.1.6.3
```

In the stacktrace of one of the games you can see that function calls end up in different versions of the library (using the demo of "Caveman Warriors"):
```
Native stacktrace:

        /usr/local/games/linux/CavemanWarriors_Data/Mono/x86_64/libmono.so(+0x91a46) [0x7f00998a7a46]
        /usr/local/games/linux/CavemanWarriors_Data/Mono/x86_64/libmono.so(+0x348e4) [0x7f009984a8e4]
        /lib64/libpthread.so.0(+0x113b0) [0x7f009ddf03b0]
        /lib64/libc.so.6(strlen+0x26) [0x7f009c617ff6]
        /lib64/libudev.so.0(+0x5b14) [0x7f0038df2b14]
        /lib64/libudev.so.0(udev_device_get_parent+0x30) [0x7f0038df2b90]
        /usr/lib64/libudev.so(udev_device_get_parent_with_subsystem_devtype+0x14) [0x7f0098297aa4]
        [0x41bba7e8]
```

Deleting the older version will get the game working.

So while I'm still not sure how to prevent this from happening it seems this is not a eudev problem.

**Comment by blueness** [comment]
I didn't answer you right away, but I did test and simply could not see how
the error arose.  Thanks for narrowing this down.
