### ISSUE TITLE
ID_SERIAL and Whitespace

### ISSUE THREAD

**Issue by msmith626** [gentoo/eudev#148]
Hi,

Using eudev 3.2.1 and noticed an issue with some NVMe drives and symbolic link creation. The links for a NVMe device look like this:
```
# udevadm info --root --query symlink --name /dev/nvme0n1
/dev/MZVPV256HDGL-000H1_S27GNY0H939193 /dev/disk/by-id/nvme-SAMSUNG /dev/disk/by-id/nvme-eui.002538696100d5bf
```

Notice the MZVPZ256HDGL... value in the root of /dev, and the "nvme-SAMSUNG" partial value in /dev/disk/by-id. It appears this is caused by whitespace in the ID_SERIAL variable value for this device:
```
# udevadm info --query=property --name /dev/nvme0n1
DEVLINKS=/dev/MZVPV256HDGL-000H1_S27GNY0H939193 /dev/disk/by-id/nvme-SAMSUNG /dev/disk/by-id/nvme-eui.002538696100d5bf
DEVNAME=/dev/nvme0n1
DEVPATH=/devices/pci0000:00/0000:00:01.0/0000:0e:00.0/nvme/nvme0/nvme0n1
DEVTYPE=disk
ID_SERIAL=SAMSUNG MZVPV256HDGL-000H1_S27GNY0H939193
ID_SERIAL_SHORT=S27GNY0H939193
MAJOR=259
MINOR=1
SUBSYSTEM=block
USEC_INITIALIZED=162712124
```

I don't know the [e]udev code well enough to determine the cause, but I suspect the "scsi_id" utility is used to get the ID_SERIAL value? I noticed "scsi_id" has a "--replace-whitespace" parameter, but when grep'ing the *.rules files, I don't see this flag being used. We're using the default rule files generated with eudev, so this may just be a configuration issue, but I'm sure other vendor/model data strings contains spaces for other devices. I've only noticed this issue with these NVMe drives.

Any hints or advice would be greatly appreciated.

Thanks,

Marc

**Comment by msmith626** [comment]
Upon digging a little deeper, I discovered the scsi_id tool is not used at all for an NVMe device (which makes sense, duh)... $attr{model} and $attr{serial} are used in the rule for the ID_SERIAL value.

I found the same issue for the systemd project:
https://github.com/systemd/systemd/issues/4833

And it appears this is the fix they used:
https://github.com/systemd/systemd/pull/4837

I'm not sure how independent the eudev project is, or if fixes/changes from systemd are pulled in at some point?

--Marc

**Comment by msmith626** [comment]
I created pull request #149 which resolves this issue.

--Marc

**Comment by blueness** [comment]
Looks good to me.  I merged it.  Can you test more at your end with master/HEAD and let me know if there's any issues.

**Comment by msmith626** [comment]
Yes, will do. Thanks.

--Marc
