### ISSUE TITLE
"input SUBSYSTEM rule in default" missing from 3.2.3

### ISSUE THREAD

**Issue by cimarronline** [gentoo/eudev#150]
It seems the commit ["rules: restore input SUBSYSTEM rule in default"](https://github.com/gentoo/eudev/commit/99e12e394fed83453ff738563e9606ed7789abd2) isn't included in the 3.2.3 release. The release's /usr/lib/udev/rules.d/50-udev-default.rules doesn't have the SUBSYSTEM=="input" line (which resulted in no touchpad, mouse, or keyboard input for me after installation; I'm running Manjaro with OpenRC).

Adding that line to 50-udev-default.rules restored proper functionality for me.

**Comment by blueness** [comment]
I need to push out 3.2.4 with the fix.  I'm just waiting a bit longer to get feedback from distros, but it definitely has to go out.

**Comment by cromerc** [comment]
This is definitely a serious problem. We experienced the same loss of keyboard, mouse, and touchpad in Cromnix and Artix linux distros. I just ended up patching 3.2.3 to fix the issue until 3.2.4 is ready.

**Comment by blueness** [comment]
okay i've pushed 3.2.4 with the fix.  thanks for your patience!

**Comment by cromerc** [comment]
Thanks for the quick resolution. 3.2.4 is confirmed working under Cromnix and Artix distros.
