### ISSUE TITLE
Consider uploading maintainer-generated tarballs

### ISSUE THREAD

**Issue by rossburton** [gentoo/eudev#151]
GitHub /archive/[tag].tar.gz tarballs (eg https://github.com/gentoo/eudev/archive/v3.2.4.tar.gz) are generated on demand and cached, so over time can and will change.  Assuming the tag never changes the extracted contents are identical but the actual tarball may have a different checksum over time.

This makes it hard to use /archive/ tarballs with distributions which verify downloaded tarballs with a checksum (such as openembedded, which uses eudev out of the box).  Would you consider uploading a static maintainer-generated tarball when you tag a release?

**Comment by blueness** [comment]
That's why I set up http://dev.gentoo.org/~blueness/eudev/

**Comment by rossburton** [comment]
Oh that's awesome.  You should consider uploading them as you make releases
to github so people like me don't bother you. :)

Ross

**Comment by blueness** [comment]
i'm not sure how to do that

**Comment by rossburton** [comment]
When you make a release (ie tag the repo) go to
https://github.com/gentoo/eudev/releases, press Create a New Release, pick
the tag, and drag the tarball you've already make into the page.  Github
will associate the tarball with the tag and let users download it.

Ross

**Comment by williamh** [comment]
I think when github generates archives, it uses "git archive" which uses the timestamp in the tag for the timestamp in the archive. Because of that, the archive's checksum will never change no matter how many times you generate the archive.

**Comment by rossburton** [comment]
On 18 September 2017 at 23:22, William <notifications@github.com> wrote:

> I think when github generates archives, it uses "git archive" which uses
> the timestamp in the tag for the timestamp in the archive. Because of that,
> the archive's checksum will never change no matter how many times you
> generate the archive.
>

Unless tar changes and the bitstream of the tarball is different (with
identical contents).  Ditto for gzip.

For a few years this has been a hypothetical situation but I've actually
seen it happen with an erlang tarball recently and Github have confirmed
that whilst they cache the tarballs, they're not stored forever.

At some point the checksum *will* change.  It's very annoying when it does
for our build system (enforced checksum validation on fetch), so I'm
preemptively removing all use of /archive/ tarballs.

Ross

**Comment by EvaSDK** [comment]
I was ready to comment about it being a documentation issue but it appears that the tarball release location is written in the readme already.

**Comment by rossburton** [comment]
In which case I apologise for not noticing that!

Ross
