### ISSUE TITLE
error: *** POSIX header not found

### ISSUE THREAD

**Issue by pandoralong** [gentoo/eudev#167]
使用：
android 的toolchain :aarch64-linux-android

configure: WARNING: langinfo.h: present but cannot be compiled
configure: WARNING: langinfo.h:     check for missing prerequisite headers?
configure: WARNING: langinfo.h: see the Autoconf documentation
configure: WARNING: langinfo.h:     section "Present But Cannot Be Compiled"
configure: WARNING: langinfo.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/gentoo/eudev/issues ##
configure: WARNING:     ## ----------------------------------------------------- ##
checking for langinfo.h... no

**Comment by blueness** [comment]
android doesn't do localization with <langinfo.h>.  luckily, it looks like nothing in this header was used and so it could safely be dropped.

please test the patch in commit 34b2037d and see if it solves your problem.  if it doesn't, please reopen this issue.
