### ISSUE TITLE
New functionality / comand line arguments

### ISSUE THREAD

**Issue by CameronNemo** [gentoo/eudev#168]
I would like to add support for a new service readiness notification mechanism to udev, and I doubt that systemd will accept a patch. I would prefer if a command line argument was used to opt into the mechanism, but it could be omitted if it would result in too great of a maintenance burden.

Please let me know your thoughts. Thank you.

**Comment by blueness** [comment]
I have to keep as close to upstream as possible.  People have suggested contributions outside of this but I have not merged them into mainstream eudev.  If you can think of a way of creating a contrib folder with optional patches, I would consider that.

**Comment by CameronNemo** [comment]
@bbonev do you want to reconsider this? s6, dinit, and other supervisors support non-forking readiness notifications but udev cannot currently operate in that way. The patch to add support is fairly small and non intrusive.

**Comment by bbonev** [comment]
OK, please reopen the PR, thus more people can review and give an opinion on it...
I haven't looked into closed issues/PRs (and do not plan to)

**Comment by bbonev** [comment]
ping @CameronNemo
