### ISSUE TITLE
@bindir@ incorrectly expands to "${exec_prefix}" in 64-btrfs.rules.in

### ISSUE THREAD

**Issue by Apteryks** [gentoo/eudev#182]
Hello, I've encountered this problem on the Guix System (c.f.: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39926#20).  The generated 64-btrfs.rules contains "${exec_prefix}", which causes (non fatal) udevd errors at boot time.

It seems the problem is probably the same as this SO question: https://stackoverflow.com/questions/54405359/how-to-recursively-substitute-variable-for-a-path-in-bash-variable-in-configure.

For reference, here's the current eudev package definition in Guix:

``` scheme
(define-public eudev
  ;; The post-systemd fork, maintained by Gentoo.
  (package
    (name "eudev")
    (version "3.2.9")
    (source (origin
              (method git-fetch)
              (uri (git-reference (url "https://github.com/gentoo/eudev")
                                  (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32
                "1g9z3d33m0i3hmbhm0wxpvkzf6ac7xj1drwcfrhzlfhhi63sg9h7"))
              (patches (search-patches "eudev-rules-directory.patch"))))
    (build-system gnu-build-system)
    (arguments
     '(#:phases
       (modify-phases %standard-phases
         (add-after 'unpack 'make-source-writable
           (lambda _
             ;; XXX: Git checkouts are read-only, but this package needs to
             ;; modify some of its files.
             (for-each make-file-writable (find-files "."))
             #t))
         (add-before 'bootstrap 'patch-file-names
           (lambda* (#:key inputs #:allow-other-keys)
            (substitute* "man/make.sh"
              (("/usr/bin/xsltproc")
                (string-append (assoc-ref inputs "xsltproc")
                               "/bin/xsltproc")))
            #t))
         (add-after 'install 'build-hwdb
           (lambda* (#:key outputs #:allow-other-keys)
             ;; Build OUT/etc/udev/hwdb.bin.  This allows 'lsusb' and
             ;; similar tools to display product names.
             (let ((out (assoc-ref outputs "out")))
               (invoke (string-append out "/bin/udevadm")
                       "hwdb" "--update")))))
       #:configure-flags (list "--enable-manpages")))
    (native-inputs
     `(("autoconf" ,autoconf)
       ("automake" ,automake)
       ("gperf" ,gperf)
       ("libtool" ,libtool)
       ("pkg-config" ,pkg-config)
       ;; For tests.
       ("perl" ,perl)
       ("python" ,python-wrapper)
       ;; For documentation.
       ("docbook-xml" ,docbook-xml-4.2)
       ("docbook-xsl" ,docbook-xsl)
       ("libxml2" ,libxml2)             ;for $XML_CATALOG_FILES
       ("xsltproc" ,libxslt)))
    (inputs
     ;; When linked against libblkid, eudev can populate /dev/disk/by-label
     ;; and similar; it also installs the '60-persistent-storage.rules' file,
     ;; which contains the rules to do that.
     `(("util-linux" ,util-linux)                 ;for blkid
       ("kmod" ,kmod)))
    (home-page "https://wiki.gentoo.org/wiki/Project:Eudev")
    (synopsis "Userspace device management")
    (description "Udev is a daemon which dynamically creates and removes
device nodes from /dev/, handles hotplug events and loads drivers at boot
time.")
    (license license:gpl2+)))
```

**Comment by blueness** [comment]
Looking at the bug at gnu.org, I think you've misconfigured the build.  Can you get me 1) the entire line that you are feeding to configure `./configure ....`  2) Run configure and at the end there is a list of variables and their replacement values including exec_bin.  Give me that entire output.

**Comment by bricewge** [comment]
[Here](http://ci.guix.gnu.org/log/zw1wvisi0hf5sb6nkysx2k10x5s50lp4-eudev-3.2.9-1) are the log for the [latest build ](http://ci.guix.gnu.org/search?query=eudev+system%3Ax86_64-linux+spec%3Aguix-master) of `eudev`.
1. The argument passed to `./configure` are listed on the line starting with `configure flags: `
2. You will find the list of variables reported by `./configure` further down

**Comment by Apteryks** [comment]
@blueness do you have the information you need?

**Comment by blueness** [comment]
@Apteryks  I'm not sure where Guix puts all its components, but I've noticed your build is not setting a lot of configure parameters.  Try the following or some variation and it should fix this problem --- vary any of the parameters to fix Guix's specifications.

`configure --prefix=/usr  --sysconfdir=/etc --localstatedir=/var/lib --exec-prefix= --bindir=/bin --includedir=/usr/include --libdir=/usr/lib --with-rootlibexecdir=/lib/udev `

**Comment by blueness** [comment]
This patch looks good.  I'll commit in a sec.
