### ISSUE TITLE
Unknown key identifier 'zoom'

### ISSUE THREAD

**Issue by dkwo** [gentoo/eudev#195]
With the last update (3.2.10), I get this error during boot.
Do you know how to fix it?
I'm on Void Linux-musl, using runit as init.
```
dmesg | grep udev
[ 0.911169] systemd-udevd[261]: starting version 3.2.9
[ 0.911334] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[ 0.911350] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[ 0.911362] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[ 0.912289] udevd[262]: starting eudev-3.2.9
[ 15.844807] udevd[671]: starting version 3.2.10
[ 15.854471] udevd[672]: starting eudev-3.2.10
[ 16.131699] udevd[690]: Unknown key identifier 'zoom'
[ 18.798458] udevd[1224]: starting version 3.2.10
[ 18.801933] udevd[1224]: starting eudev-3.2.10
```
Also, is it expected to have so many instances of udevd?
Thanks.

**Comment by dkwo** [comment]
Copy /lib/udev/hwdb.d/60-keyboard.hwdb to /etc/udev/hwdb.d/ and comment out every line with `=zoom`, then
```
udevadm hwdb --update
udevadm control --reload-rules
udevadm trigger
```

**Comment by ktnlikeasmallcat** [comment]
Also getting `Unknown key identifier 'zoom'` on void, doing the 60-keyboard.hwdb fix did not effect the error.
https://github.com/fwupd/firmware-lenovo/issues/106

**Comment by stuff97** [comment]
Hello @ktnlikeasmallcat , did you manage to find a fix for it ?

Edit, actually @dkwo fix works perfectly fine but do we know why is this happening ? I have a Thinkpad X1 yoga on Void
