### ISSUE TITLE
"make dist" fails due to html documentation missing

### ISSUE THREAD

**Issue by axs-gentoo** [gentoo/eudev#79]
make[2]: Entering directory `/path/to/eudev-workdir/docs'
 (cd libudev && make  top_distdir=../../eudev-1.3 distdir=../../eudev-1.3/docs/libudev \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/path/to/eudev-workdir/docs/libudev'
make  \
  top_distdir="../../eudev-1.3" distdir="../../eudev-1.3/docs/libudev" \
  dist-hook
make[4]: Entering directory `/path/to/eudev-workdir/docs/libudev'
cp: cannot stat ‘./html/*’: No such file or directory
make[4]: *** [dist-hook] Error 1
make[4]: Leaving directory `/path/to/eudev-workdir/docs/libudev'
make[3]: *** [distdir] Error 2

..this is with git HEAD as of today; gtk-doc is installed, and ./configure --enable-gtk-doc specified.  Seems to not matter what other gtk-doc flags I set, though; I can't get it to keep from failing here.  Either gtk-doc isn't generating the html docs or there's some stuff in the build system we committed from upstream that shouldn't be there, I think.

**Comment by blueness** [comment]
laziness pays off.  gtk-docs is gone upstream and commit 1b6370e removes it from eudev.
