### ISSUE TITLE
q: plans when udev becomes systemd-only ? (after kdbus merge)

### ISSUE THREAD

**Issue by msoltyspl** [gentoo/eudev#95]
Hi,

This is question regarding following mention I found on systemd mailinglist:

"Also note that at that point [kdbus merge] we intend to move udev onto kdbus as
transport, and get rid of the userspace-to-userspace netlink-based
tranport udev used so far. Unless the systemd-haters prepare another
kdbus userspace until then this will effectively also mean that we will
not support non-systemd systems with udev anymore starting at that
point."

More details in following two posts (thread: "Drop the udev firmware loader"):

http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/19440/focus=19510
http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/19440/focus=19517

If I'm reading this correctly, this change will in essence kill udev for non-systemd scenarios. Whether new kernels will support non-kdbus based udev is also interesting question. Normally new kernel/old userspace should function fine for a good while ...

**Comment by blueness** [comment]
I don't know what else to say on this bug excep that we are aware of the kdbus work and we'll have to deal with that when the time comes.
